# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  after_all do |lane| 
    # clean_build_artifacts()
     notification(title:"Success",subtitle:"#{scheme} #{version}",message:lane.to_s,sound:"Default")
     UI.message "Success Build #{scheme} #{version} in lane #{lane.to_s} "
   end
 
   error do |lane, exception|
     # Send error notification
     notification(title:"Failure on #{scheme} #{version}",subtitle:lane.to_s,message:exception.to_s,sound:"Default")
     raise "Failure on #{scheme} #{version} \n in lane #{lane.to_s} \n exception = #{exception.to_s}"
     clean_build_artifacts()
   end

   desc "Run App Unit tests on given devices name"
  lane :run_ci_tests do |options|

        UI.message "The device raw : #{options[:device]}"
        device =  options[:device]
        UI.message "The device list : #{device}"
        
        clean = false 

        if options[:clean] then 
          clean = options[:clean]
        end

        open_report = false 

        if options[:open_report] then 
          open_report = options[:open_report]
        end

        scan(clean: clean, # clean project folder before test execution    
          device: device, # Devices for testing     
          configuration: "Debug",
          open_report: open_report)
  end

end
