# This is a basic workflow to help you get started with Actions

name: Document Generator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [document]
  push:
    branches:
      - infrastracture/CI
      - develop
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  document:
    name: Generate Documentions
    runs-on: macOS-latest
    steps:
        - name: Checkout Branch
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: | 
            pod install 
        - name: Publish Jazzy Docs
          uses: Steven0351/publish-jazzy-docs@v1.1.2
          with:  
            # Arguments to pass to Jazzy
            args: "--theme fullwidth --author 'Farshad Mousalou' --min-acl internal --build-tool-arguments -workspace,YouTV-App.xcworkspace,-scheme,YouTVDemo --module YouTVDemo --clean"
            # Personal access token
            personal_access_token: ${{ secrets.GITHUB_TOKEN }}
            branch: docs
        - name: Running Jazzy 
          run: |
            bundle install --verbose
            bundle exec fastlane run jazzy
       
