# This is a basic workflow to help you get started with Actions

name: Document Generator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [document]
  push:
    branches:
      - infrastracture/CI
      - develop
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  document:
    name: Generate Documentions
    runs-on: macOS-latest
    steps:
        - name: Checkout Branch
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: | 
            bundle install  --verbose
            bundle exec pod install
        - name: Running Jazzy 
          run: |
            bundle exec fastlane run jazzy
