# This is a basic workflow to help you get started with Actions

name: Document Generator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [document]
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  document:
    name: Generate Docs
    runs-on: macOS-latest
    steps:
        - name: Checkout Branch
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: | 
            bundle install
            bundle exec pod install 
        - name: Generate Jazzy Docs
          id: generate
          run: |
            git fetch -a -p
            git branch -vv
            git status && git add . && git reset --hard
            export currentBranch=$(git branch -vv | grep '*' | awk '{ print $2 }' | xargs)
            git checkout docs
            git pull origin --force
            git merge $currentBranch --verbose -X theirs --ff -m "- Merge ${currentBranch} into docs at $(date +'%Y-%m-%d')"
            jazzy --author 'Farshad Mousalou' --min-acl private --build-tool-arguments -workspace,YouTVDemo.xcworkspace,-scheme,YouTVDemo --module YouTVDemo --clean --output Docs/
            git add ./Docs/* 
            echo "::set-output name=message::Updated Project Docs at $(date +'%Y-%m-%d')"
        - name: Publish Jazzy Docs
          uses: actions-js/push@master  
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            message: ${{ steps.generate.outputs.message }}
            branch: docs
            force: true
            directory: './Docs'
